### PR TITLE
Improvements to SSDP discovery and associated tests

### PR DESCRIPTION
**Pull request by bjmc**
I was running into some errors using the SSDP discovery `ControlPoint()` with my camera, so this is an attempt to clean up and improve the SSDP discovery logic.

The two main changes in `pysony.py` are:

* Don't `break` out of the loop early in `_listen_for_discover()` -- I think this was the source of my bug, because it wasn't listening long enough to get the response from my camera.
* Use XML libraries to parse the device definition file, instead of regex. I think this should be a lot easier to maintain and more reliable across different camera models.

I've also added tests for SSDP discovery, including some dummy services to test against, and updated the README to include docs on running tests. 

There's some minor overlap with #57, but I think the conflicts will be easy to resolve.

### CODE REVIEW

**Comment by bjmc** [comment]
This might help with #33 if their issue is the same timeout problem as mine.

**Comment by bjmc** [comment]
This might also fix #23 since one of the comments theorizes the issue is with the regular expression parsing.

**Comment by bjmc** [comment]
Changed base branch to `develop` -- is that right @Bloodevil?

**Comment by Bloodevil** [comment]
> Changed base branch to `develop` -- is that right @Bloodevil?

yep it is right. thanks!

**Comment by Bloodevil** [comment]
I  merge it to develop.

**Pull request merged**
